version: '2'
services:
    factory-app:
        image: factory
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://factory-postgresql:5432/Factory
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=factory-elasticsearch:9300
        ports:
            - 8080:8080
    factory-postgresql:
        extends:
            file: postgresql.yml
            service: factory-postgresql
    factory-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: factory-elasticsearch
